//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BookCollect
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class IBookEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“IBookEntities”部分中的连接字符串初始化新 IBookEntities 对象。
        /// </summary>
        public IBookEntities() : base("name=IBookEntities", "IBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 IBookEntities 对象。
        /// </summary>
        public IBookEntities(string connectionString) : base(connectionString, "IBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 IBookEntities 对象。
        /// </summary>
        public IBookEntities(EntityConnection connection) : base(connection, "IBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Books> Books
        {
            get
            {
                if ((_Books == null))
                {
                    _Books = base.CreateObjectSet<Books>("Books");
                }
                return _Books;
            }
        }
        private ObjectSet<Books> _Books;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Books EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBooks(Books books)
        {
            base.AddObject("Books", books);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IBookModel", Name="Books")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Books : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Books 对象。
        /// </summary>
        /// <param name="iSBN">ISBN 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="author">Author 属性的初始值。</param>
        /// <param name="lang">Lang 属性的初始值。</param>
        /// <param name="score">Score 属性的初始值。</param>
        /// <param name="votes">Votes 属性的初始值。</param>
        /// <param name="onBoard">OnBoard 属性的初始值。</param>
        /// <param name="dataSource">DataSource 属性的初始值。</param>
        /// <param name="entryTime">EntryTime 属性的初始值。</param>
        /// <param name="readMark">ReadMark 属性的初始值。</param>
        /// <param name="newMark">NewMark 属性的初始值。</param>
        public static Books CreateBooks(global::System.String iSBN, global::System.String title, global::System.String author, global::System.String lang, global::System.Decimal score, global::System.Int32 votes, global::System.Boolean onBoard, global::System.String dataSource, global::System.DateTime entryTime, global::System.Boolean readMark, global::System.Boolean newMark)
        {
            Books books = new Books();
            books.ISBN = iSBN;
            books.Title = title;
            books.Author = author;
            books.Lang = lang;
            books.Score = score;
            books.Votes = votes;
            books.OnBoard = onBoard;
            books.DataSource = dataSource;
            books.EntryTime = entryTime;
            books.ReadMark = readMark;
            books.NewMark = newMark;
            return books;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                if (_ISBN != value)
                {
                    OnISBNChanging(value);
                    ReportPropertyChanging("ISBN");
                    _ISBN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ISBN");
                    OnISBNChanged();
                }
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lang
        {
            get
            {
                return _Lang;
            }
            set
            {
                OnLangChanging(value);
                ReportPropertyChanging("Lang");
                _Lang = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lang");
                OnLangChanged();
            }
        }
        private global::System.String _Lang;
        partial void OnLangChanging(global::System.String value);
        partial void OnLangChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Score
        {
            get
            {
                return _Score;
            }
            set
            {
                OnScoreChanging(value);
                ReportPropertyChanging("Score");
                _Score = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Score");
                OnScoreChanged();
            }
        }
        private global::System.Decimal _Score;
        partial void OnScoreChanging(global::System.Decimal value);
        partial void OnScoreChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Votes
        {
            get
            {
                return _Votes;
            }
            set
            {
                OnVotesChanging(value);
                ReportPropertyChanging("Votes");
                _Votes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Votes");
                OnVotesChanged();
            }
        }
        private global::System.Int32 _Votes;
        partial void OnVotesChanging(global::System.Int32 value);
        partial void OnVotesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean OnBoard
        {
            get
            {
                return _OnBoard;
            }
            set
            {
                OnOnBoardChanging(value);
                ReportPropertyChanging("OnBoard");
                _OnBoard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnBoard");
                OnOnBoardChanged();
            }
        }
        private global::System.Boolean _OnBoard;
        partial void OnOnBoardChanging(global::System.Boolean value);
        partial void OnOnBoardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataSource
        {
            get
            {
                return _DataSource;
            }
            set
            {
                OnDataSourceChanging(value);
                ReportPropertyChanging("DataSource");
                _DataSource = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DataSource");
                OnDataSourceChanged();
            }
        }
        private global::System.String _DataSource;
        partial void OnDataSourceChanging(global::System.String value);
        partial void OnDataSourceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryTime
        {
            get
            {
                return _EntryTime;
            }
            set
            {
                OnEntryTimeChanging(value);
                ReportPropertyChanging("EntryTime");
                _EntryTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryTime");
                OnEntryTimeChanged();
            }
        }
        private global::System.DateTime _EntryTime;
        partial void OnEntryTimeChanging(global::System.DateTime value);
        partial void OnEntryTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ReadMark
        {
            get
            {
                return _ReadMark;
            }
            set
            {
                OnReadMarkChanging(value);
                ReportPropertyChanging("ReadMark");
                _ReadMark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadMark");
                OnReadMarkChanged();
            }
        }
        private global::System.Boolean _ReadMark;
        partial void OnReadMarkChanging(global::System.Boolean value);
        partial void OnReadMarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NewMark
        {
            get
            {
                return _NewMark;
            }
            set
            {
                OnNewMarkChanging(value);
                ReportPropertyChanging("NewMark");
                _NewMark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewMark");
                OnNewMarkChanged();
            }
        }
        private global::System.Boolean _NewMark;
        partial void OnNewMarkChanging(global::System.Boolean value);
        partial void OnNewMarkChanged();

        #endregion

    
    }

    #endregion

    
}
